\documentclass[pdflatex, a4paper, 11pt]{article}
\usepackage{booktabs, longtable, adjustbox, array, enumerate, mathtools, fancyhdr, graphicx, fancybox, amsmath, lscape, caption}
\usepackage[hmargin=2.5cm,vmargin=3.5cm]{geometry}
\usepackage[utf8]{inputenc}
\usepackage[table]{xcolor}
\usepackage[T1]{fontenc}
\usepackage[affil-it]{authblk}

%%% Hyperref and cref settings
\usepackage[bookmarksnumbered]{hyperref} % hyperlinks
\hypersetup{colorlinks,breaklinks,
            urlcolor=blue,%[rgb]{0.29020,0.52157,0.56078},
            linkcolor=blue,%[rgb]{0.29020,0.52157,0.56078},
            citecolor=blue,%[rgb]{00.29020,0.52157,0.56078},
            linktoc=page}

\captionsetup{labelformat=empty}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\textbf{Report}}
\fancyhead[R]{\textit{nca\_ppc}}
\fancyfoot[C]{\thepage}
\numberwithin{equation}{section}
\numberwithin{figure}{section}
\numberwithin{table}{section}
\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{4pt}}m{#1}}
\title{\textbf{Report of \textit{nca\_ppc} package}}
\author{Chayan Acharya, Andrew C. Hooker, Siv Jonsson, Mats O. Karlsson}
\affil{Department of Pharmaceutical Biosciences\\Uppsala University, Sweden}
\date{\vspace{-5ex}}
\begin{document}
\raggedright{}
\maketitle
\thispagestyle{empty}

\newpage{}
\tableofcontents
\thispagestyle{empty}
\clearpage
\pagenumbering{arabic}

\section{Summary of the data set and the results}

<<main, echo=FALSE>>=
spread   <- fnOut$spread
nsim     <- fnOut$NSIM
txt      <- fnOut$TXT
prnTab   <- fnOut$prnTab
pddf     <- fnOut$pddf
conc     <- fnOut$conc
histobs  <- fnOut$histobs
pop      <- fnOut$pop
dev      <- fnOut$dev
outlier  <- fnOut$outlier
forest   <- fnOut$forest
npde     <- fnOut$npde
histnpde <- fnOut$histnpde
sprtxt   <- ifelse(spread=="sd", "standard deviation", "95% nonparametric prediction interval of the PK measures obtained from the simulated data")
@

<<txt, echo=FALSE>>=
cat(txt)
@

\paragraph{}
\begin{center}
\textbf{Summary table}
<< Summary table, echo=FALSE, results='asis'>>==
require(xtable)
print(xtable(pddf, align=rep("c",ncol(pddf)+1), rotate.colnames = T), file=paste(usrdir,"/sum.tex",sep=""), include.rownames=FALSE,
      tabular.environment="longtable", caption.placement = "top", size="\\tiny", floating=FALSE)
@
\input{sum}
\end{center}
\paragraph{}

\section{Description of the tabular output}

<<child = if (nsim == 0) 'figTabNoSim.Rnw', echo=FALSE>>=
@

<<child = if (nsim != 0) 'figTab.Rnw', echo=FALSE>>=
@

\end{document}