\documentclass[pdflatex, a4paper, 11pt]{article}
\usepackage{booktabs, longtable, adjustbox, array, enumerate, mathtools, fancyhdr, graphicx, fancybox, amsmath, lscape, caption}
\usepackage[hmargin=2.5cm,vmargin=3.5cm]{geometry}
\usepackage[utf8]{inputenc}
\usepackage[table]{xcolor}
\usepackage[T1]{fontenc}
\usepackage[affil-it]{authblk}
\usepackage{needspace}
\usepackage{listings}
\usepackage{inconsolata}

%%% Hyperref and cref settings
\usepackage[bookmarksnumbered]{hyperref} % hyperlinks
\hypersetup{colorlinks,breaklinks,
            urlcolor=blue,%[rgb]{0.29020,0.52157,0.56078},
            linkcolor=blue,%[rgb]{0.29020,0.52157,0.56078},
            citecolor=blue,%[rgb]{00.29020,0.52157,0.56078},
            linktoc=page}

\captionsetup{labelformat=empty}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\textbf{Report}}
\fancyhead[R]{\textit{ncappc}}
\fancyfoot[C]{\thepage}
\numberwithin{equation}{section}
\numberwithin{figure}{section}
\numberwithin{table}{section}
\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{4pt}}m{#1}}
\title{\textbf{Report of \textit{ncappc}\textsuperscript{*} package}}
\author{\vspace{-0cm}}
\date{\today}

\begin{document}
\raggedright{}
\maketitle
\thispagestyle{empty}

\vfill
\textit{\textsuperscript{*} \textbf{ncappc} package is created and maintained by:}
\newline
\textit{Chayan Acharya, Andrew C. Hooker, Siv Jonsson, Mats O. Karlsson}
\newline
\textit{Department of Pharmaceutical Biosciences, Uppsala University, Sweden}
\clearpage

\newpage{}
\footnotesize
\tableofcontents
\thispagestyle{empty}
\clearpage
\pagenumbering{arabic}

<<echo=FALSE>>=
options(width=60)
listing <- function(x, options){
  paste("\\begin{lstlisting}[basicstyle=\\ttfamily,breaklines=true]\n",
  x, "\\end{lstlisting}\n", sep = "")
}
knit_hooks$set(source=listing, output=listing)
@

\section{Summary of the data set and the results}

<<main, echo=FALSE>>=
arglist  <- fnOut$arglist
txt      <- fnOut$TXT
pddf     <- fnOut$pddf
prnTab   <- fnOut$prnTab
nsim     <- fnOut$NSIM
conc     <- fnOut$conc
histobs  <- fnOut$histobs
pop      <- fnOut$pop
dev      <- fnOut$dev
outlier  <- fnOut$outlier
forest   <- fnOut$forest
npde     <- fnOut$npde
histnpde <- fnOut$histnpde
hth      <- fnOut$phth
wth      <- fnOut$pwth

if(fnOut$spread=="ppi"){
  sprtxt <- "95\\% parametric prediction interval of the NCA metrics"
}else if(fnOut$spread=="npi"){
  sprtxt <- "95\\% nonparametric prediction interval of the NCA metrics"
}
@

<<txt, echo=FALSE, tidy=TRUE>>=
cat(txt)
@
\paragraph{}


\begin{center}
\textbf{Summary table}
<< Summary table, echo=FALSE, results='asis'>>==
require(xtable)
mtable <- xtable(pddf, align=c(rep("c",ncol(pddf)-3),"p{3cm}","p{1cm}","p{1cm}","p{2cm}"), rotate.colnames = T)
print(mtable, file=paste(usrdir,"/sum.tex",sep=""), include.rownames=FALSE,
      tabular.environment="longtable", caption.placement = "top", size="\\tiny", floating=FALSE)
@
\input{sum}
\end{center}
\paragraph{}

\footnotesize
\section{Command-line arguments passed to ncappc function}
<<cmd, echo=FALSE, listing=FALSE,source=FALSE,output=FALSE>>=
print(arglist)
@

\newpage
\footnotesize
\section{Description of the tabular output}

% Figure and Table description in the presence of simulated data
\begin{sloppypar}

\subsection{Table 1 (ncaOutput.tsv)}
Estimated NCA metrics using the observed and simulated concentration-time profile. Brief description of the column names: \textbf{ID} = individual ID, \textbf{AUClast} = AUC from the time of dose to the time of the last sampled plasma concentration estimated from the observed data, \textbf{simAUClast} = mean AUC from the time of dose to the time of the last sampled plasma concentration estimated from \Sexpr{round(nsim)} sets of simulated data, \textbf{dAUClast} = deviation of simAUClast from AUClast scaled by the "spread" (\Sexpr{sprtxt}) of the simulated AUClast, \textbf{npdeAUClast} = Normalized prediction distribution error (NPDE) of AUClast. Similar annotation was used for the other NCA metrics.

\paragraph{}
\begin{center}
\textbf{Table 1. ncaOutput.tsv (selected columns of top 100 rows)}
<< Final table, echo=FALSE, results='asis'>>==
require(xtable)
print(xtable(prnTab, align=rep("c",ncol(prnTab)+1), rotate.colnames = T), file=paste(usrdir,"/tab.tex",sep=""), include.rownames=FALSE,
      tabular.environment="longtable", caption.placement = "top", size="\\tiny", floating=FALSE)
@
\input{tab}
\end{center}
\paragraph{}

\footnotesize
\subsection{Table 2 (Obs\_Stat.tsv)}
A set of statistical parameters calculated for the population groups for Tmax, Cmax, AUClast, AUClower\_upper, AUCINF\_obs, AUC\_pExtrap\_obs, AUCINF\_pred, AUC\_pExtrap\_pred, AUMClast, AUMCINF\_obs, AUMC\_pExtrap\_obs, AUMCINF\_pred, AUMC\_pExtrap\_pred, HL\_Lambda\_z, Rsq, Rsq\_adjusted, No\_points\_Lambda\_z obtained from the observed data. Brief description of the calculated statistical parameters: \textbf{Ntot} = Total number of data points, \textbf{Nunique} = number of unique data points, \textbf{Min} = minimum value, \textbf{Max} = maximum value, \textbf{Mean} = mean/average value, \textbf{SD} = standard deviation, \textbf{SE} = standard error, \textbf{CVp} = coefficient of variation \%, \textbf{a95CIu} = upper limit of 95\% arithmetic confidence interval, \textbf{a95CIl} = lower limit of 95\% arithmetic confidence interval, \textbf{gMean} = geometric mean, \textbf{gCVp} = geometric coefficient of variation \%.

\subsection{Table 3 (Sim\_Stat.tsv)}
A set of statistical parameters calculated for the population groups for Tmax, Cmax, AUClast, AUClower\_upper, AUCINF\_obs, AUC\_pExtrap\_obs, AUCINF\_pred, AUC\_pExtrap\_pred, AUMClast, AUMCINF\_obs, AUMC\_pExtrap\_obs, AUMCINF\_pred, AUMC\_pExtrap\_pred, HL\_Lambda\_z, Rsq, Rsq\_adjusted, No\_points\_Lambda\_z obtained from the estimated data. Brief description of the calculated statistical parameters: \textbf{Ntot} = Total number of data points, \textbf{Nunique} = number of unique data points, \textbf{Min} = minimum value , \textbf{Max} = maximum value, \textbf{Mean} = mean/average value, \textbf{SD} = standard deviation, \textbf{SE} = standard error, \textbf{CVp} = coefficient of variation \%, \textbf{a95CIu} = upper limit of 95\% arithmetic confidence interval, \textbf{a95CIl} = lower limit of 95\% arithmetic confidence interval, \textbf{gMean} = geometric mean, \textbf{gCVp} = geometric coefficient of variation \%.

\subsection{Table 4 (ncaSimData.tsv)}
Simulated concentration-time profiles for each individual obtained from each simulation. "NSUB" column denotes the simulation number.

\subsection{Table 5 (ncaSimEst.tsv)}
Estimated NCA metrics for each individual using the simulated concentration-time profile obtained from each simulation. "NSUB" column denotes the simulation number.


\newpage
\section{Description of the graphical output}

\subsection{Figure 1. [Individual level] Concentration \textit{vs.} time profile}
<<concplot, echo=FALSE, fig.pos="H", out.width='0.9\\textwidth', fig.align="center">>=
if (length(conc)>0){
  for (i in 1:length(conc)){suppressMessages(suppressWarnings(grid.draw(conc[[i]]))); Sys.sleep(0.5); grid.newpage()}
}else{
  print("No concentration vs time plot is available.")
}
@

Concentration vs time profile for each individual stratified by dose or population group, if any, as obtained from the observed data. The left panels represent the raw data, while the right panels represent the semi-logarithmic form of the concentration data. Each of the lines represents individual data.

\newpage
\subsection{Figure 2. [Population level] Histogram of the selected NCA metrics estimated from the observed data}
<<histobsplot, echo=FALSE, fig.pos="H", out.width='0.9\\textwidth', fig.align='center'>>=
if (length(histobs)>0){
  suppressPackageStartupMessages(require(gridExtra))
  for (i in 1:length(histobs)){suppressMessages(suppressWarnings(grid.draw(histobs[[i]]))); Sys.sleep(0.5); grid.newpage()}
}else{
  cat("No histogram is available as the number of individuals is less than 5 in\nall population strata!")
}
@

Histogram of four selected NCA metrics (AUClast, AUCINF\_obs, Cmax, Tmax) estimated from the observed data. The solid blue vertical and dotted lines represent the population mean and the "spread" of the data. The "spread" is defined by \Sexpr{sprtxt} obtained from the observed data.

\newpage
\subsection{Figure 3. [Population level] Histogram of the simulated population means of the NCA metrics}
<<popplot, echo=FALSE, fig.pos="H", fig.height=8, fig.width=4, out.width='0.9\\textwidth', fig.align='center'>>=
if (length(pop)>0){
  suppressPackageStartupMessages(require(gridExtra))
  for (i in 1:length(pop)){suppressMessages(suppressWarnings(grid.draw(pop[[i]]))); Sys.sleep(0.5); grid.newpage()}
}else{
  print("No plot is available.")
}
@

Histogram of the population mean of the NCA metrics obtained from the simulated data from the \Sexpr{round(nsim)} simulations. The red and blue solid vertical lines represent the population mean of the NCA metric obtained from the observed data and the mean of the population means of the same NCA metric obtained from the \Sexpr{round(nsim)} number of simulations, respectively. The blue dashed vertical lines represent the "spread" of the simulated distribution. The "spread" is defined by \Sexpr{sprtxt} obtained from the simulated data.

\newpage
\subsection{Figure 4. [Individual level] Deviation of the simulated NCA metrics from the observed value}
<<devplot, echo=FALSE, fig.pos="H", out.width='0.9\\textwidth', fig.align='center'>>=
if (length(dev)>0){
  for (i in 1:length(dev)){suppressMessages(suppressWarnings(print(dev[[i]]))); Sys.sleep(0.5)}
}else{
  print("No plot is available.")
}
@

Deviation of the mean of the NCA metrics for each individual estimated from the simulated data obtained from \Sexpr{round(nsim)} simulations (meanSim) from the corresponding values estimated from the observed data (Obs). The deviation is scaled by the boundary of the "spread" of the simulated data (\Sexpr{sprtxt}) proximal to the observed value (\textbf{Deviation = (Obs - meanSim)/ spread}). The negative value of the deviation signifies over-prediction of the corresponding NCA metric, while a positive value of the deviation signifies under-prediction of the same.

\newpage
\subsection{Figure 5. [Individual level] Distribution of the simulated NCA metrics for the outliers}
<<outlierplot, echo=FALSE, fig.pos="H", out.width='0.9\\textwidth', fig.align='center'>>=
if (length(outlier)>0){
  suppressPackageStartupMessages(require(gridExtra))
  for (i in 1:length(outlier)){suppressMessages(suppressWarnings(grid.draw(outlier[[i]]))); Sys.sleep(0.5); grid.newpage()}
}else{
  cat("No outlier plot is available as the number of outlier is 0!")
}
@

Distribution of the NCA metrics obtained from the simulated data for the outlier individuals. The individuals are labelled as outliers because the absolute value of the scaled deviation for at least one of the NCA metrics used in diagnosis is larger than 1. The red and blue solid vertical lines represent the observed NCA metric value and the mean of the simulated NCA metric values for that individual, respectively. The dashed blue vertical lines represent the "spread" (\Sexpr{sprtxt}) of the simulated distribution.

\newpage
\subsection{Figure 6. [Population level] Forest plot for the NPDE type analysis}
<<forestplot, echo=FALSE, fig.pos="H", out.width='0.9\\textwidth', fig.align='center'>>=
if (length(forest)>0){
  for (i in 1:length(forest)){suppressMessages(suppressWarnings(print(forest[[i]]))); Sys.sleep(0.5)}
}else{
  print("No plot is available.")
}
@

Forest plot of the NPDE type analysis displaying the mean and standard deviation of the NPDE vaues of the NCA metrics for different population groups. The red and green dots represent the mean and the standard deviation of the NPDE, respectively while the horizontal red and green lines represent the corresponding 95\% confidence intervals.

\newpage
\subsection{Figure 7. [Individual level] NPDE values of the NCA metrics for each individual}
<<npdeplot, echo=FALSE, fig.pos="H", out.width='0.9\\textwidth', fig.align='center'>>=
if (length(npde)>0){
  for (i in 1:length(npde)){suppressMessages(suppressWarnings(print(npde[[i]]))); Sys.sleep(0.5)}
}else{
  print("No plot is available.")
}
@

NPDE values of the NCA metrics for each individual within a given population group calculated from the corresponding observed and simulated values of the NCA metrics. The negative value of the NPDE signifies over-prediction of the corresponding NCA metric, while a positive value of the NPDE signifies under-prediction of the same.

\newpage
\subsection{Figure 8. [Population level] Histogram of the NPDE values of the NCA metrics within a given population group}
<<histnpdeplot, echo=FALSE, fig.pos="H", out.width='0.9\\textwidth', fig.align='center'>>=
if (length(histnpde)>0){
  for (i in 1:length(histnpde)){suppressMessages(suppressWarnings(print(histnpde[[i]]))); Sys.sleep(0.5)}
}else{
  print("No plot is available.")
}
@

Histogram of the NPDE values of the NCA metrics for all individuals within a given population group. The red solid vertical represents the mean of the ideal NPDE distribution, which is the theoretical normal distribution (mean=0, SD=1). The blue solid vertical lines represent the mean of the NPDE distribution for the corresponding population group. The dashed blue vertical lines represent the standard deviation of the distribution of the NPDE values within that population group.

\end{sloppypar}
\end{document}

