---
title: "CommandLineArguments"
output: rmarkdown::html_vignette
---

**Name** | **Description** | **Example of possible values** | **Default**
:-------:|:---------------:|:------------------------------:|:-----------:
obsFile | Observed concentration-time data from an internal data frame or an external table with comma, tab or space as separator | File name or data frame | **"nca_original.npctab.dta"**
simFile | Simulated concentration-time data in NONMEM format from an internal data frame or an external table | File name or data frame | **"nca_simulation.1.npctab.dta"**
str1Nm | Column name for 1st level population stratifier | Column name | **NULL**
str1 | Stratification ID within 1st level stratification | c(1,2) | **NULL**
str2Nm | Column name for 2nd level population stratifier | Column name | **NULL**
str2 | Stratification ID within 2nd level stratification | c(1,2) | **NULL**
str3Nm | Column name for 3rd level population stratifier | **NULL**
str3 | Stratification ID within 3rd level stratification | c(1,2) | **NULL**
concUnit | Unit of concentration | "ng/mL" | **"M.L^-3"**
timeUnit | Unit of time | "h" | **"T"**
doseUnit | Unit of dose amount | "mg" | **"M"**
doseNormUnit | Normalization factor of dose amount if used | kg | **NULL**
obsLog | Concentration in observed data in logarithmic form | Logical (TRUE or FALSE) | **FALSE**
simLog | Concentration in simulated data in logarithmic form | Logical (TRUE or FALSE) | **FALSE**
psnOut | observed data is an output from PsN or in NONMEM output format | Logical (TRUE or FALSE) | **FALSE**
idNmObs | Column name for ID in observed data | Column name | **"ID"**
timeNmObs | Column name for time in observed data | Column name | **"TIME"**
concNmObs | Column name for concentration in observed data | Column name | **"DV"**
idNmSim | Column name for ID in simulated data | Column name | **"ID"**
timeNmSim | Column name for time in simulated data | Column name | **"TIME"**
concNmSim | Column name for concentration in simulated data | Column name | **"DV"**
AUCTimeRange | User-defined window of time used to estimate AUC | c(0,24) | **NULL**
backExtrp | If back-extrapolation is needed for AUC | Logical (TRUE or FALSE) | **FALSE**
LambdaTimeRange | User-defined window of time to estimate elimination rate-constant | c(15,24) | **NULL**
LambdaExclude | User-defined excluded observation time points for estimation of elimination rate-constant | c(20,22) | **NULL**
doseAmtNm | Column name to specify dose amount | Cokumn name | **NULL**
adminType | Route of administration | iv-bolus, iv-infusion, extravascular | **"extravascular"**
doseType | Steady-state (ss) or nonsteady-state (ns) dose | "ss" or "ns" | **"ns"**
doseTime | Dose time prior to the first observation for steady-state data | Numeric | **NULL**
Tau | Dosing interval for steady-state data | Numeric | **NULL**
TI | Infusion duration | Numeric | **NULL**
method | Computational method to estimate AUC and AUMC | linear, log or linear-log | "linear-log" | **"linear-log"**
blqNm | Name of BLQ column if used | Column name | **NULL**
blqExcl | Excluded BLQ value or logical condition | 1, ">=1", c(1,">3") | **"1"**
evid | Use EVID data to filter data | Logical (TRUE or FALSE) | **TRUE**
evidIncl | EVID values used to filter data | Numeric |**0**
mdv | Use MDV dat to filter data | Logical (TRUE or FALSE) | **FALSE**
filterNm | Column name for filter | Column name | **NULL**
filterExcl | Filter identifier or logical condition used for row exclusion | c(1, 2, "<20", ">=100", "!=100") | **NULL**
negConcExcl | Exclude negative concentration | Logical (TRUE or FALSE) | **FALSE**
param | NCA metrics used for diagnostics | c(AUClast, AUClower_upper, AUCINF_obs, AUCINF_pred, AUMClast, Cmax, Tmax, HL_Lambda_z) | **c("AUClast", "Cmax")**
timeFormat | Data format for time | "number", "H:M", "H:M:S") | **"number"**
dateColNm | Name of the date column | Column name | **NULL**
dateFormat | Data format for date | "D-M-Y", "D/M/Y" or any other combination of "D,M,Y" | **NULL**
spread | Measure of the spread of simulated data | "ppi" (95\% parametric prediction interval) or "npi" (95\% nonparametric prediction interval)) | **"npi"**
tabCol | Output columns to be printed in the report in addition to ID, dose and population strata information | list of NCA metrics in a string array | **c("AUClast", "Cmax", "Tmax", "AUCINF_obs", "Vz_obs", "Cl_obs", "HL_Lambda_z")**
figFormat | Format of the produced figures | "bmp", "jpeg", "tiff", "png" | **"tiff"**
noPlot | Perform only NCA calculations without any plot generation | Logical (TRUE or FALSE) | **FALSE**
printOut | Write/print output on the disk. No plot will be saved if noPlot is set to TRUE | Logical (TRUE or FALSE) | **TRUE**
studyName | Name of the study to be added as a description in the report | Study name | **NULL**
new_data_method | For testing a faster method of reading data | Logical (TRUE or FALSE) | **TRUE**
overwrite_SIMDATA | Create new information in the SIMDATA directory, or to use the information in the SIMDATA | TRUE, FALSE or NULL | **NULL**
outFileNm | Additional tag to the name of the output html and pdf output file hyphenated to the standard ncappc report file name | Output file name tag | **Name of the observed data file**


**obsFile**
The name of the file containing the observed concentration vs. time data. This is a mandatory argument and the default value to this argument is the generic output from PsN, ***"nca_original.npctab.dta"***. The columns within the observed data file must be separated by either comma or space or tab.

**simFile**
The name of the file containing the NONMEM output of the concentration vs. time data simulated using the PK model to be diagnosed. The default value to this argument is the generic output from PsN, ***"nca_simulation.1.npctab.dta"***. When this argument is set NULL, ***ncappc*** function performs only the traditional NCA; otherwise, ***ncappc*** function performs the traditional NCA as well as the diagnostic tests for the related PK model

**str1Nm, str2Nm and str3Nm**
All three of them individually can be used to specify the column name within the data set defining the population group when used separately. E.g., if there is only one stratification criteria for the population, any of these 3 arguments can be used to identify the stratification column name. When str1Nm is used together with either str2Nm or str3Nm, str1Nm defines the column name for the upper level stratification and str2Nm/str3Nm defines the column name for the lower level stratification. When all three of them are used together, str1Nm, str2Nm and str3Nm define the column names of the upper, middle and lower stratification levels, respectively. The default value for these arguments are ***NULL***.

**str1, str2 and str3**
str1, str2 and str3 are identfiers for the population stratifications, present in the corresponding stratification levels defined by str1Nm, str2Nm and str3Nm columns, respectively. The default value for this argument is ***NULL***. If the str1Nm, str2Nm or str3Nm arguments are non-empty, but the corresponding str1, str2 or str3 arguments are left as NULL, this function will use the unique values from the str1Nm, str2Nm or str3Nm column as identifiers for the members of the corresponding population strata.

**concUnit**
The unit of plasma concentration values (e.g. "ng/mL"). The default value for this argument is the dimension of concentration ***[M].[L]^-3***.

**timeUnit**
The unit of time intervals (e.g. "hr"). The default value for this argument is the dimension of time ***[T]***.

**doseUnit**
Unit for the dosage amount (e.g. "ng"). The default value for this argument is the dimension of mass ***[M]***.

**doseNormUnit**
Normalization factor for the dosage amount (e.g. body weight in "kg"). The default value for this argument is ***NULL***.

**obsLog and simLog**
These arguments decide if the concentration values in the observed and simulated data sets are in logarithmic form. The accepted input to these arguments is either TRUE or FALSE. The default value for these arguments is ***FALSE***.

**psnOut**
It is possible to generate the input file with the observed data using PsN. This argument lets the function know if the input data is in PsN or NONMEM output format. The possible values to this argument are TRUE and FALSE, ***FALSE*** being the default value.

**idNmObs and idNmSim**
Column name for individual ID in observed and simulated data. The default value for this argument is ***"ID"***.

**timeNmObs and timeNmSim**
Column name for time in observed and simulated data. The default value for this argument is ***"TIME"***.

**concNmObs and concNmSim**
Column name for plasma concentration in observed and simulated data. The default value for this argument is ***"DV"***.

**AUCTimeRange**
This argument lets the user to choose a specific window of time to be used to estimate AUC. The accepted format for the input to this argument is a numeric array of two elements; c(1,24) will estimate the AUC values within 1st to 24th unit of time interval. The default value for this argument is ***NULL***.

**backExtrp**
This argument lets the user to choose if the back extrapolation for the area estimatation is performed from rhe first observed data to dosing time. The default value for this argument is ***FALSE***.

**LambdaTimeRange**
This argument lets the user to choose a specific window of time to be used to estimate the elimination rate constant (Lambda) in the elimination phase after the last observed data. The accepted format for the input to this argument is a numeric array of two elements; c(14,24) will estimate the Lambda using the data within the 14th to 24th unit of time interval. The default value for this argument is ***NULL***.

**LambdaExclude**
This argument lets the user exclude observation time points for the estimation of elimination rate-constant (Lambda) in the elimination phase. The accepted format for the input to this argument is a numeric array of time points; c(8,10) will exclude time points 8 and 10 while estimating the Lambda. The default value for this argument is ***NULL***.

**doseAmtNm**
Column name to specify the dose amount. This argument is unused if the value of the dose amount is provided in the "doseAmt" argument. If the "doseAmt" argument is empty, the value of the dose amount is extracted from the column specified in this argument or from the "AMT" column. The default value for this argument is ***"AMT"***.

**adminType**
This argument is used to specify the route of the drug administration. The allowed values for this argument are "iv-bolus", "iv-infusion" and "extravascular". The default route of administration is ***"extravascular"***

**doseType**
This argument is used to specify either the steady-state ("ss") or the nonsteady-state ("ns") dosage types. The default value to this argument is ***"ns"***.

**doseTime**
doseTime is the dose time prior to the first observation for steady-state data. If the *doseType* argument is assigned to "ss" and doseTime is *NULL*, steady state observation period will be estimated based on the first non-zero obverved concentration and Tau. The default value to this argument is ***NULL***.

**Tau**
The dosing interval for the steady-state data. This is a mandatory argument if the *doseType* argument is assigned to "ss". The default value to this argument is ***NULL***.

**TI**
The infusion duration for the steady-state data. If the argument is empty, TI is calculated from the "RATE" and "AMT" values. This is a mandatory argument if the *doseType* argument is assigned to "ss" and the input data file does not contain "RATE" and "AMT" columns. The default value to this argument is ***NULL***.

**method**
The user is allowed to choose the method of area estimation (AUC, AUMC). The "linear" option uses linear trapezoidal method of area estimation; while the "log" method uses logarithmic trapezoidal method. The "linear-log" option uses the linear trapezoidal approximation for the ascending part of the curve and logarithmic trapezoidal approximation for the descending part of the curve during the area estimation. The default value for this argument is ***"linear-log"***.

**blqNm**
Name of the BLQ data column, if the user decides to filter the input based on BLQ data. The default value for this argument is ***NULL***, which means the BLQ column will not be used to filter.

**blqExcl**
The BLQ values that will be used to filter the input data. This argument will be used only if the "blqNm" argument is non-empty. This argument accepts either numeric values and/or logical conditions (e.g. 1, ">=1", c(1,">3")). The default value for this argument is ***1***.

**evid**
This argument decides if the EVID column will be used to filter the input data. The accepted input to this argument is either TRUE or FALSE. The default value for this argument is ***TRUE***.

**evidIncl**
This arguments accepts the values of the EVID data that will included for the calculations. This argument is used only if the "evid" argument is non-empty. The default value for this argument is ***0***.

**mdv**
This argument decides if the MDV column will be used to filter the input data. The accepted input to this argument is either TRUE or FALSE. The default value for this argument is ***FALSE***. If chosen TRUE, all rows with MDV = 0 will be selected for the calculations.

**filterNm**
The name of the column that will be used to filter the input data. The default value for this argument is ***NULL***.

**filterExcl**
This arguments accepts the values from the "filterNm" column that will used to exclude rows form the input data. This argument accepts either string/numeric values and/or logical conditions (e.g. "a", 1, c(1,2), "<20",
">=100", "!=100", c(1,">3"), or c("a","3")). This argument is used only if the *"filterNm"* argument is non-empty. The default value for this argument is ***NULL***.

**negConcExcl**
This argument is used to exclude the data with negative concentration values. The accepted input to this argument is either TRUE or FALSE. The default value for this argument is ***FALSE***.

**param**
This argument lists the NCA metrics that will be used to perform the diagnostic tests. Any combination of the following NCA metrics can be assigned to this argument: "AUClast", "AUClower_upper", "AUCINF_obs", "AUCINF_pred", "AUMClast", "Cmax", "Tmax", "HL_Lambda_z". The default value for this argument is ***c("AUClast","Cmax")***.

**timeFormat**
The data format for the time column. The accepted formats are numerical values, "H:M" or "H:M:S". The default value for this argument is ***"number"***, which signifies the numerical values.

**dateColNm**
This function allows the user to combine the information from the "DATE" column with the "TIME" column to calculate the time difference between the observations. This argument accepts the name of the date column, if used to calculate the time difference. The default value for this argument is ***NULL***.

**dateFormat**
The data format for the date column. The accepted formats are "D-M-Y", "D/M/Y" or any otehr combination of D, M and Y. The default value for this argument is ***NULL***.

**spread**
This argument determines the metric that will be used to measure the spread of the simulated distribution of the NCA metrics. The spread argument accepts either "ppi" or "npi" as input. The "ppi" uses 95% parametric prediction interval, while "npi" uses the 95% nonparametric prediction interval. The default value for this argument is ***"npi"***.

**tabCol**
This argument selects the table columns, in addition to ID, dose and population strata, to print in the produced report. This argument accepts a list of NCA metrics in a string array. The default value of this argument is ***c("AUClast", "Cmax", "Tmax", "AUCINF_obs", "Vz_obs", "Cl_obs", "HL_Lambda_z")***.

**figFormat**
This argument selects the format of the produced figures. Acceptable value for this argument is either bmp, jpeg, tiff or png. The default value is ***"tiff"***.

**noPlot**
This argument can turn on/off plot generation during NCA calculations. Acceptable value for this argument is either TRUE (turns off plot generation) or FALSE (turns on plot generation). The default value is ***FALSE***.

**printOut**
This argument lets the user decide if the ncappc generated figures and tables will be saved on the disk. Acceptable value for this argument is either TRUE or FALSE. The default value is ***TRUE***.

**studyName**
Name of the study to be added as a description in the report. The default value for this argument is ***NULL***.

**outFileNm**
Additional tag to the name of the output html and pdf output file hyphenated to the standard ncappc report file name. The default value for this argument is the ***name of the observed data file***.

